# Generated by Django 4.1.4 on 2023-01-14 19:03

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="Create at"
            ),
        ),
    ]
