exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: ^backend/

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        files: ^backend/
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        files: ^frontend/

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd frontend && npm run lint"
        language: node
        additional_dependencies:
          - "@next/eslint-plugin-next@^13.1.0"
          - "@types/node@18.11.17"
          - "@types/react@18.0.26"
          - "@types/react-dom@18.0.9"
          - "@typescript-eslint/eslint-plugin@^5.47.0"
          - "@typescript-eslint/parser@^5.47.0"
          - "eslint@8.30.0"
          - "eslint-config-next@13.0.7"
          - "eslint-config-prettier@^8.5.0"
          - "eslint-import-resolver-node@^0.3.6"
          - "eslint-import-resolver-typescript@^3.5.2"
          - "eslint-plugin-import@^2.26.0"
          - "eslint-plugin-jsx-a11y@^6.6.1"
          - "eslint-plugin-next@^0.0.0"
          - "eslint-plugin-react@^7.31.11"
          - "eslint-plugin-react-hooks@^4.6.0"
          - "next@13.0.7"
          - "prettier@2.8.1"
          - "typescript@4.9.4"
# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
# ci:
#   autoupdate_schedule: weekly
#   skip: []
#   submodules: false
