version: '3'

services:
  django: &django
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    image: lem_local_django
    container_name: lem_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/src:z
      - static_files:/src/staticfiles:z
    env_file:
      - ./.envs/local/django.env
      - ./.envs/local/postgres.env
    ports:
      - "8000:8000"
    command: /start-django.sh

    networks:
      - lem_local_backend_frontend_ngnix
      - lem_local_backend_db

  postgres:
    image: postgres:15-alpine
    container_name: lem_local_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/local/postgres.env
    networks:
      - lem_local_backend_db

  redis:
    image: redis:7
    container_name: lem_local_redis
    networks:
      - lem_local_backend_db

  celeryworker:
    <<: *django
    image: lem_local_celeryworker
    container_name: lem_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh

    networks:
      - lem_local_backend_db

  celerybeat:
    <<: *django
    image: lem_local_celerybeat
    container_name: lem_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh
    networks:
      - lem_local_backend_db

  flower:
    <<: *django
    image: lem_local_flower
    container_name: lem_local_flower
    ports:
      - "5555:5555"
    command: /start-flower.sh
    networks:
      - lem_local_backend_db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: lem_local_frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - django
    networks:
      - lem_local_backend_frontend_ngnix

  nginx:
    build: ./nginx
    container_name: lem_local_ngnix
    ports:
      - 4000:80
    volumes:
      - static_files:/staticfiles/:z
    depends_on:
      - django
      - frontend
    networks:
      - lem_local_backend_frontend_ngnix

networks:
  lem_local_backend_db:
    name: lem_local_backend_db
  lem_local_backend_frontend_ngnix:
    name: lem_local_backend_frontend_ngnix

volumes:
  postgres_data:
  static_files:
