[tool.poetry]
name = "lem"
version = "0.1.0"
description = ""
authors = ["Sebastian Nieciąg <68351270+sebanie15@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
